routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StagiaireController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
Route::resource('stagiaire', StagiaireController::class);

app/Models/Stagiaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stagiaire extends Model
{
    use HasFactory;
    protected $fillable= ["nom_complet","genre", "date_naissance", "note","groupe_id"];
    protected $casts=[
    'date_naissance' => 'datetime:Y-m-d',
        ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/StagiaireController.php
<?php

namespace App\Http\Controllers;

use App\Models\Stagiaire;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StagiaireController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $stagiaires=Stagiaire::all();
        return view("stagiaire.index", compact("stagiaires"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("stagiaire.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $stagiaire = Stagiaire::create([
            "nom_complet"=>$request->nom_complet,
            "genre"=>$request->genre,
            "date_naissance"=>$request->date_naissance,
            "note"=>$request->note,
            "groupe_id"=>$request->groupe_id,
        ]);
        
        return redirect()->route('stagiaire.create')->with('success','Le stagiaire a été ajouté avec succès.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Stagiaire $stagiaire)
    {
        return view("stagiaire.show", compact("stagiaire"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Stagiaire $stagiaire)
    {
        return view("stagiaire.edit", compact("stagiaire"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Stagiaire $stagiaire)
    {
        
        // $stagiaire->nom_complet=$request->nom_complet;
        // $stagiaire->genre=$request->genre;
        // $stagiaire->date_naissance=$request->date_naissance;
        //  $stagiaire->note=$request->note;
        // $stagiaire->groupe_id=$request->groupe_id;
        //$stagiaire->save();

        $stagiaire->update($request->all());
        return redirect()->route('stagiaire.index')->with('success','Le stagiaire a été modifié avec succès.');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Stagiaire $stagiaire)
    {
        $stagiaire->delete();
         return redirect()->route('stagiaire.index')->with('success','Le stagiaire a été supprimé avec succès.');

    }
}

resources/views/stagiaire/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Document</title>
</head>
 
<body class="container mt-2">
      @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
<h2>Nouveau stagiaire</h2>
   <form class="col-8" method="post" action="{{route('stagiaire.store')}}">
       @csrf
  <div class="mb-3">
    <label for="nom_complet" class="form-label">Nom complet</label>
    <input type="text" class="form-control" id="nom_complet" name="nom_complet"/>
  </div>
    <div class="mb-3">
        <label for="genre" class="form-label">Genre : </label>
        <div class="form-check form-check-inline">
            <input class="form-check-input " type="radio" name="genre" id="genre_f" value="F">
            <label class="form-check-label" for="genre_f"> F </label>
        </div>
         <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre" id="genre_m" value="M">
            <label class="form-check-label" for="genre_m"> M </label>
        </div>
    </div>
    <div class="mb-3">
        <label for="date_naissance" class="form-label">Date de naissance</label>
        <input type="date" class="form-control" id="date_naissance" name="date_naissance"/>
    </div>
    <div class="mb-3">
        <label for="note" class="form-label">Note</label>
        <input type="text" class="form-control" id="note" name="note"/>
    </div>
    <div class="mb-3">
        <label for="groupe_id" class="form-label">Groupe</label>
        <input type="text" class="form-control" id="groupe_id" name="groupe_id"/>
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

resources/views/stagiaire/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Modification</title>
</head>
 
<body class="container mt-2">
      @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
<h2>Modifier un stagiaire</h2>
   <form class="col-8" method="post" action="{{route('stagiaire.update', $stagiaire->id)}}">
       @csrf
       @method('PUT')
  <div class="mb-3">
    <label for="nom_complet" class="form-label">Nom complet</label>
    <input type="text" class="form-control" id="nom_complet" name="nom_complet" value="{{ $stagiaire->nom_complet }}"/>
  </div>
    <div class="mb-3">
        <label for="genre" class="form-label">Genre : </label>
        <div class="form-check form-check-inline">
            <input class="form-check-input " type="radio" name="genre" id="genre_f" value="F" {{ ($stagiaire->genre == 'F')? 'checked': null }}>
            <label class="form-check-label" for="genre_f"> F </label>
        </div>
         <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre" id="genre_m" value="M" {{ ($stagiaire->genre == 'M')? 'checked': null }}>
            <label class="form-check-label" for="genre_m"> M </label>
        </div>
    </div>
    <div class="mb-3">
        <label for="date_naissance" class="form-label">Date de naissance</label>
        <input type="date" class="form-control" id="date_naissance" name="date_naissance" value="{{ $stagiaire->date_naissance->format('Y-m-d') }}"/>
    </div>
    <div class="mb-3">
        <label for="note" class="form-label">Note</label>
        <input type="text" class="form-control" id="note" name="note" value="{{ $stagiaire->note }}"/>
    </div>
    <div class="mb-3">
        <label for="groupe_id" class="form-label">Groupe</label>
        <input type="text" class="form-control" id="groupe_id" name="groupe_id" value="{{ $stagiaire->groupe_id }}"/>
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

resources/views/stagiaire/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Liste des stagiaires</title>
</head>
<body class="container">
    <h2 class="mt-3">Liste des stagiaires</h2>
     @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
    @isset($stagiaires)
        <table class="table mt-3">
            <tr>
                <th>Id</th>
                <th>Nom complet</th>
                <th>Genre</th>
                <th>Date de naissance</th>
                <th>Note</th>
                <th>Groupe</th>
                <th>Action</th>
            </tr>
            @foreach($stagiaires as $stagiaire)
                <tr>
                    <td>{{ $stagiaire->id }}</td>
                    <td>{{ $stagiaire->nom_complet }}</td>
                    <td>{{ $stagiaire->genre }}</td>
                    <td>{{  $stagiaire->date_naissance->format('d/m/Y') }}</td>
                    <td>{{ $stagiaire->note }}</td>
                    <td>{{ $stagiaire->groupe_id }}</td>
                    <td>
                        <form method="post" action="{{ route('stagiaire.destroy', $stagiaire->id) }}">
								@csrf
								@method('DELETE')
								<a href="{{ route('stagiaire.show', $stagiaire->id) }}" class="btn btn-primary btn-sm">Afficher</a>
								<a href="{{ route('stagiaire.edit', $stagiaire->id) }}" class="btn btn-warning btn-sm">Modifier</a>
								<input type="submit" class="btn btn-danger btn-sm" value="Supprimer" />
							</form>
                    </td>
                    <td></td>
                </tr>
            @endforeach
        </table>
    @endisset
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

resources/views/stagiaire/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container mt-4">
        <h2> Détails</h2>
        <div class="form-group">
            <strong>Nom complet :</strong>
            {{ $stagiaire->nom_complet }}
        </div>
        <div class="form-group">
           <strong>Genre :</strong>
           {{ $stagiaire->genre }}
        </div>
        <div class="form-group">
            <strong>Date de naissance :</strong>
            {{ $stagiaire->date_naissance->format("d/m/Y") }}
        </div>
        <div class="form-group">
            <strong>Note :</strong>
            {{ $stagiaire->note }}
        </div>
        <div class="form-group">
            <strong>Groupe :</strong>
            {{ $stagiaire->groupe_id }}
        </div>
        <div class="form-group">
            <strong>Création :</strong>
            {{ $stagiaire->created_at->format("d/m/Y H:i") }}
        </div>
        <div class="form-group">
            <strong>Dernière modification :</strong>
            {{ $stagiaire->updated_at->format("d/m/Y H:i") }}
        </div>
       </div>
 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>